version: '3.8'

services:
  data-capture-app:
    image: rps/data-capture:1.0.0
    ports:
      - "8501:8501"
    volumes:
      - ../models:/app/models
      - ../data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
  
  training-app:
    image: rps/training:1.0.0
    ports:
      - "8502:8501"
    volumes:
      - ../models:/app/models
      - ../data:/app/data
    environment:
      - PYTHONUNBUFFERED=1